"""User-facing YAML aliases for AirSim sensor and camera keys."""
from __future__ import annotations

SENSOR_FIELD_ALIASES = {
    "sensor_type": "SensorType",
    "enabled": "Enabled",
    "pressure_factor_sigma": "PressureFactorSigma",
    "eph_time_constant": "EphTimeConstant",
    "epv_time_constant": "EpvTimeConstant",
    "eph_initial": "EphInitial",
    "epv_initial": "EpvInitial",
    "eph_final": "EphFinal",
    "epv_final": "EpvFinal",
    "eph_min_3d": "EphMin3d",
    "eph_min_2d": "EphMin2d",
    "update_latency": "UpdateLatency",
    "update_frequency": "UpdateFrequency",
    "startup_delay": "StartupDelay",
    "external_controller": "ExternalController",
    "number_of_channels": "NumberOfChannels",
    "channels": "NumberOfChannels",
    "rotations_per_second": "RotationsPerSecond",
    "points_per_second": "PointsPerSecond",
    "measurements_per_cycle": "MeasurementsPerCycle",
    "points_per_scan": "PointsPerScan",
    "range": "Range",
    "vertical_fov_upper": "VerticalFOVUpper",
    "vertical_fov_lower": "VerticalFOVLower",
    "horizontal_fov_start": "HorizontalFOVStart",
    "horizontal_fov_end": "HorizontalFOVEnd",
    "draw_debug_points": "DrawDebugPoints",
    "ignore_marked": "IgnoreMarked",
    "generate_noise": "GenerateNoise",
    "draw_sensor": "DrawSensor",
    "x": "X",
    "y": "Y",
    "z": "Z",
    "roll": "Roll",
    "pitch": "Pitch",
    "yaw": "Yaw",
}

CAMERA_FIELD_ALIASES = {
    "x": "X",
    "y": "Y",
    "z": "Z",
    "roll": "Roll",
    "pitch": "Pitch",
    "yaw": "Yaw",
}

CAPTURE_FIELD_ALIASES = {
    "image_type": "ImageType",
    "width": "Width",
    "height": "Height",
    "fov_degrees": "FovDegrees",
    "fov": "FovDegrees",
    "fovdegrees": "FovDegrees",
    "auto_exposure_speed": "AutoExposureSpeed",
    "exposure_compensation": "ExposureCompensation",
    "scene_type": "SceneType",
    "motion_blur_amount": "MotionBlurAmount",
    "fisheye_model": "FisheyeModel",
    "fisheye_fx": "FisheyeFx",
    "fisheye_fy": "FisheyeFy",
    "fisheye_cx": "FisheyeCx",
    "fisheye_cy": "FisheyeCy",
    "fisheye_k1": "FisheyeK1",
    "fisheye_k2": "FisheyeK2",
    "fisheye_k3": "FisheyeK3",
    "fisheye_k4": "FisheyeK4",
    "fisheye_p1": "FisheyeP1",
    "fisheye_p2": "FisheyeP2",
    "fisheye_enable_barrel_distortion": "FisheyeEnableBarrelDistortion",
    "fisheye_cube_resolution": "FisheyeCubeResolution",
    "fisheye_capture_depth": "FisheyeCaptureDepth",
    "fisheye_capture_segmentation": "FisheyeCaptureSegmentation",
    "fisheye_circular_mask": "FisheyeCircularMask",
    "fisheye_sensor_mode": "FisheyeSensorMode",
    "fisheye_shm_publish_enabled": "FisheyeShmPublishEnabled",
    "enable_optical_effects": "EnableOpticalEffects",
    "panorama_enabled": "panorama_enabled",
    "panorama_cube_resolution": "panorama_cube_resolution",
    "panorama_width": "panorama_width",
    "panorama_height": "panorama_height",
}

CAMERA_CAPTURE_KEYS = set(CAPTURE_FIELD_ALIASES)
