#!/usr/bin/env bash
# Smoke-test the per-drone bridges against compose/ardupilot-xfs.
#
# Prereq: their main stack (docker-compose.yml) is up — AirSim available at
# host:41451 and the SITL fleet running. Run separately first.
#
# Usage:
#   ./test-per-drone-bridges.sh                # run full test
#   ./test-per-drone-bridges.sh --no-regen     # skip the bridges.yml regen
#   ./test-per-drone-bridges.sh --teardown     # bring everything down

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
COSYS_AIRSIM_REPO="${COSYS_AIRSIM_REPO:-/home/mnsuser/Cosys_Airsim_Exploration}"
COSYS_AIRSIM_BRANCH="${COSYS_AIRSIM_BRANCH:-feat/multi-agent-ros2-zenoh-architecture}"
GEN_PATH_IN_REPO="integrations/ros2/docker/Linux/multi-agent/generate_compose.py"
WAIT_SEC="${WAIT_SEC:-30}"

cmd="${1:-run}"
case "$cmd" in
  --teardown|teardown)
    docker compose -f "$HERE/docker-compose.bridge-test.yml" down 2>/dev/null || true
    if [[ -f "$HERE/docker-compose.bridges.override.yml" ]]; then
      docker compose -f "$HERE/docker-compose.bridges.yml" \
        -f "$HERE/docker-compose.bridges.override.yml" down 2>/dev/null || true
    else
      docker compose -f "$HERE/docker-compose.bridges.yml" down 2>/dev/null || true
    fi
    docker compose -f "$HERE/docker-compose.networks.yml" down 2>/dev/null || true
    echo "torn down"
    exit 0
    ;;
  --no-regen)
    REGEN=0
    ;;
  *)
    REGEN=1
    ;;
esac

echo "=== creating per-drone networks ==="
# Bypass `docker compose up --no-start` on networks.yml: that file's only
# service is gated by profile=never, and compose v2 rejects an `up` with
# zero selected services ("no service selected"). Create idempotently.
for n in 1 2 3 4; do
  if ! docker network inspect "agent_internal-${n}" >/dev/null 2>&1; then
    docker network create \
      --subnet="172.28.${n}.0/24" \
      --gateway="172.28.${n}.254" \
      "agent_internal-${n}" >/dev/null
    echo "  created agent_internal-${n}"
  else
    echo "  agent_internal-${n} exists"
  fi
done

if [[ "$REGEN" -eq 1 ]]; then
  echo "=== regenerating bridges-only compose (Copter prefix, 4 drones) ==="
  # Prefer the vendored generator under tools/. Falls back to git-show on the
  # Cosys-AirSim feat branch only if the vendored copy is missing — useful if
  # the vendored copy ever gets accidentally deleted.
  vendored_gen="$HERE/tools/generate_compose.py"
  if [[ -x "$vendored_gen" ]]; then
    echo "    using vendored generator: tools/generate_compose.py"
    python3 "$vendored_gen" --drones 4 --mode integration --vehicle-prefix Copter \
      --output "$HERE/docker-compose.bridges.yml"
  else
    echo "    vendored generator missing, falling back to git-show on $COSYS_AIRSIM_BRANCH"
    tmp_gen="$(mktemp --suffix=.py)"
    trap 'rm -f "$tmp_gen"' EXIT
    git -C "$COSYS_AIRSIM_REPO" show "${COSYS_AIRSIM_BRANCH}:${GEN_PATH_IN_REPO}" > "$tmp_gen"
    python3 "$tmp_gen" --drones 4 --mode integration --vehicle-prefix Copter \
      --output "$HERE/docker-compose.bridges.yml"
  fi
fi

echo "=== bringing up per-drone bridges ==="
# Layer the local X11 override in. See docker-compose.bridges.override.yml
# for why — the vendored bridges file uses an X11-enforcing image that
# refuses to start without DISPLAY + the X11 socket bound in.
BRIDGES_COMPOSE_FILES=( -f "$HERE/docker-compose.bridges.yml" )
if [[ -f "$HERE/docker-compose.bridges.override.yml" ]]; then
  BRIDGES_COMPOSE_FILES+=( -f "$HERE/docker-compose.bridges.override.yml" )
  echo "    layering local override: docker-compose.bridges.override.yml"
fi
# The scenario-local .env (auto-generated by compose/setup-env.sh) sets
# AIRSIM_HOST_IP=127.0.0.1 — correct for the host-network main stack but
# unreachable from the bridges' isolated agent_internal-N networks. Force
# host.docker.internal here unless the caller explicitly overrode it.
export AIRSIM_HOST_IP="${AIRSIM_HOST_IP_OVERRIDE:-host.docker.internal}"
echo "    AIRSIM_HOST_IP=$AIRSIM_HOST_IP"
docker compose "${BRIDGES_COMPOSE_FILES[@]}" up -d

echo "=== bringing up test consumers ==="
docker compose -f "$HERE/docker-compose.bridge-test.yml" up -d

echo "=== waiting ${WAIT_SEC}s for bridges to discover vehicles ==="
sleep "$WAIT_SEC"

echo
echo "=== verifying topics per drone ==="
fail=0
for n in 1 2 3 4; do
  echo "--- Copter${n}  (test container on agent_internal-${n}, ROS_DOMAIN_ID=${n}) ---"
  topics=$(docker exec "ardupilot-xfs-bridge-test-d${n}" bash -lc \
    "source /opt/ros/humble/setup.bash && ros2 topic list" 2>&1 || true)
  if echo "$topics" | grep -q "^/Copter${n}/"; then
    count=$(echo "$topics" | grep -c "^/Copter${n}/")
    echo "  PASS: ${count} /Copter${n}/* topics visible"
    echo "$topics" | grep "^/Copter${n}/" | head -5 | sed 's/^/    /'
  else
    echo "  FAIL: no /Copter${n}/* topics from inside agent_internal-${n}"
    echo "  Got these instead:"
    echo "$topics" | head -10 | sed 's/^/    /'
    fail=1
  fi
  echo
done

if [[ "$fail" -eq 0 ]]; then
  echo "=== ALL DRONES PASSED ==="
else
  echo "=== ONE OR MORE DRONES FAILED ==="
fi
exit "$fail"
